# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lakshan-028' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lakshan-028

  target 'Lakshan-028Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Lakshan-028UITests' do
    # Pods for testing
  end

end

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'SwiftQRScanner', :git => ‘https://github.com/vinodiOS/SwiftQRScanner’